name: Link Checker
description: A GitHub Action to check links on a website.
author: merlos

inputs:
  url:
    description: 'The base URL to start scraping from'
    required: false
    default: 'http://localhost:4444/'
  only-errors:
    description: 'Only display errors'
    required: false
    default: 'false'
  ignore-file:
    description: 'Path to the ignore file'
    required: false
    default: './check-ignore'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.only-errors }}
    - ${{ inputs.ignore-file }}

branding:
  icon: 'link'
  color: 'blue'
